name: Test Build Steps

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-15
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.44.6'
          channel: stable
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16'
      - name: Flutter pub get
        run: flutter pub get
      - name: Install fastlane
        run: sudo gem install fastlane --no-document
      - name: Test
        run: |
          echo "Done!"
